### PR TITLE
All "Learn more" buttons below algorithm are updated now!

### LINKED ISSUE #253: Learn More button is not Functional
### Describe the bug
The "Learn More" button below algorithms (e.g., Binary Search) currently scrolls the page up instead of directly linking to the relevant algorithm documentation. This creates unnecessary navigation steps for the user. The button should instead link directly to the algorithm's detailed page.

### To Reproduce
Go to the [site](https://ajay-dhangar.github.io/algo/).
Scroll down to the Binary Search algorithm.
Click "Learn More" and observe that the page scrolls up instead of opening the detailed documentation.

### Expected behavior
Clicking the "Learn More" button should take the user directly to the relevant algorithm's page, such as:

Binary Search: https://ajay-dhangar.github.io/algo/docs/binary-search/iterative-binary-search-DSA

### Additional context
Solution: Update the "Learn More" button's href attribute to link directly to the corresponding algorithm documentation.

---

**Would you like to work on this issue?**  
- [x] Yes , I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Saaarthak0102**
Description

Updated all "Learn More" buttons below algorithms to directly link to the corresponding detailed algorithm pages. This improves user navigation by preventing unnecessary page scrolling. Each button now takes the user directly to the relevant page (e.g., iterative binary search).

Fixes # 253 : 

Type of change:

 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 Documentation update

Checklist:

 My code follows the style guidelines of this project
 I have performed a self-review of my code
 I have commented my code, particularly in hard-to-understand areas
 New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Saaarthak0102** [comment]
Please add labels for gssoc-24 extd and level

**Comment by Saaarthak0102** [comment]
Please review and merge @ajay-dhangar

**Comment by ajay-dhangar** [comment]
> Please review and merge @ajay-dhangar

@Saaarthak0102, your pr is empty so, push your code

**Comment by Saaarthak0102** [comment]
> > Please review and merge @ajay-dhangar
> 
> @Saaarthak0102, your pr is empty so, push your code

I have made changes in the "index.html" file in  "build" folder....But i have realized my mistake now, modifying the source codes!
help me if i am wrong ...new here! 
@ajay-dhangar

**Pull request closed without merging**
