### PR TITLE
solved #650 and #724

### LINKED ISSUE #650: [Feature Request]add challenge 3 and show results
### Is your feature request related to a problem? Please describe.
add challenge 3 and show results

### Describe the solution you'd like
add challenge 3 and show results.

### Describe alternatives you've considered
add challenge 3 and show results
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #650 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
adv1
adv2
solved #650

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
solved #724
ds-3
ds-2

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir it is ready to merge

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir could you merge this pull request

**Comment by ajay-dhangar** [comment]
Please wait one day before we need to maintain our "all contributors" point (max 200 points).

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
ok sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
kindly change the level to level3 sir

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
