### PR TITLE
Principal component analysis

### LINKED ISSUE #1586: [Idea]: Principal Component Analysis
### Idea Title

Principal Component Analysis

### Idea Description

Principal Component Analysis (PCA) is a dimensionality reduction technique widely used in machine learning and statistics. It transforms a dataset into a new coordinate system, where the greatest variance by any projection lies on the first coordinate (the first principal component), the second greatest variance on the second coordinate, and so on. PCA is particularly useful for simplifying datasets while retaining their essential characteristics, making it easier to visualize and analyze high-dimensional data.

@ajay-dhangar kindly assign me this issue along with the labels

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [X] Other

### Implementation Suggestions (Optional)

_No response_

### PR DESCRIPTION
**Pull request by KGupta2601**
### Description
added principal component analysis.

Fixes #1586 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by KGupta2601** [comment]
@ajay-dhangar please review my PR

**Comment by KGupta2601** [comment]
@ajay-dhangar kindly review my PR and provide the labels

**Comment by KGupta2601** [comment]
@ajay-dhangar sir please review my PR

**Review by ajay-dhangar — APPROVED** [review]
Done

**Review by ajay-dhangar — APPROVED** [review]
✔️

**Pull request merged**
