### PR TITLE
Best Meeting Point to Top DSA interview questions 

### LINKED ISSUE #1949: [Custom]: <ADD A PROBLEM>Best Meeting Point to Top DSA interview questions
### Issue Summary

Best Meeting Point

### Issue Description

Problem: Given a 2D grid of 0s and 1s, where each 1 represents the home of one friend, find the best meeting point that minimizes the total travel distance.
Type: Math, Median, Grid Traversal.
Hint: Find median coordinates separately for rows and columns.

### Proposed Solution (Optional)

_No response_

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

### Additional Context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by shriyadindi**
### Description
Best Meeting Point to Top DSA interview questions 

Fixes #1949

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ajay-dhangar** [comment]
This branch has conflicts that need to be resolved before the changes can be merged. Can you resolve the conflicts?

**Comment by shriyadindi** [comment]
@ajay-dhangar I've resolved the conflicts, kindly review.

**Comment by shriyadindi** [comment]
@ajay-dhangar why did you close this PR? If there are merge conflicts I'll resolve them
https://github.com/ajay-dhangar/algo/pull/1957#event-15237720835

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar why did you close this PR? If there are merge conflicts I'll resolve them [#1957 (comment)](https://github.com/ajay-dhangar/algo/pull/1957#event-15237720835)

Because we need to make our code more optimized so, I'll change my code in more better way because this time my heap is large

**Comment by shriyadindi** [comment]
@ajay-dhangar okay

**Pull request merged**
