### PR TITLE
Adding rem quizzes

### LINKED ISSUE #553: Adding remaining quizzes
@ajay-dhangar 
There are only 2 quizzes available, for remaining topics quiz is not available, i would like to quiz for all the remaining
quiz

### LINKED ISSUE #554: Issue Title: "Add Chatbot Feature"
@ajay-dhangar 
Issue Description: I would like to add a chatbot feature to the website to enhance user support and engagement. The chatbot will provide instant assistance to users by answering common queries, offering guidance, and directing them to relevant sections of the site.

Please assign this issue to me under the labels: level3, gssoc-ext, and hacktoberfest-accepted.

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@ajay-dhangar 
I have added all the quizzes successfully

https://github.com/user-attachments/assets/8b9b5c80-44b5-4413-9602-f00d157f0f2f

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar could you please change the level to 3, i have added all the quizzes

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar could you please merge this, i have added all the quizzes and conside it as level3, it took so much effort to collect all the information

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar solved the merge conflicts

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar could you help why it is showing like this 
hack

**Pull request merged**
