### PR TITLE
solved #782  added solutions to challenges 

### LINKED ISSUE #758: [Bug] Solve warning Duplicate routes found!

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
changes:
1.changed questions of challenge 2 as both challeneg 1,2 displaying same questions
2.added solutions to challenge 1
3.add solutions to challenge 2
added solutions to challenges 

Fixes #758

https://github.com/user-attachments/assets/bd1cda03-9c30-4a06-8080-3774257c92ba

image
image
image

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please change level to level 3 and merge it sir

https://github.com/user-attachments/assets/234e0ac3-2aea-4502-9588-2bd57782fd9c

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@ajay-dhangar sir please merge this pr

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Can you create a directory for this in the docs? We need to write in the src using good format and follow best practices. Therefore, we can't put your code in the src.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
