### PR TITLE
solved #754 #720 #721

### LINKED ISSUE #720: [Feature Request] <Title of your feature>Add solutions to the quiz on arrays
### Is your feature request related to a problem? Please describe.
Add solutions to the quiz on arrays

### Describe the solution you'd like
Add solutions to the quiz on arrays
### Describe alternatives you've considered
Add solutions to the quiz on arrays
### Additional context
Add solutions to the quiz on arrays
---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### LINKED ISSUE #721: [Feature Request] Add solutions ,explanation to the quiz on stacks as a reference to the students
### Is your feature request related to a problem? Please describe.
Add solutions to the quiz on stacks
### Describe alternatives you've considered
Add solutions ,explanation to the quiz on stacks as a reference to the students 
### Additional context
Add solutions ,explanation to the quiz on stacks as a reference to the students 
---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### LINKED ISSUE #754: [Feature Request] <Title of your feature>Add quizes solutions page
### Is your feature request related to a problem? Please describe.
Add quizes solutions page
### Describe the solution you'd like
Add quizes solutions page
### Describe alternatives you've considered
Add quizes solutions page
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description

Fixes # (issue number)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
### SOLVED #754 
quizsol1
quizsol2

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
### solved #720 
arraysol

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
### Fixed #721 
stacksol1

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
### Solved 3 issues in the same pull request#755
issues: #720 #721 #754 
kindly consider it as level 3 and allot marks for solving the 3 issues and my efforts sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir could you please merge this pull request

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
