### PR TITLE
Addition of Leetcode Solutions 1-10 | Issue #173

### LINKED ISSUE #173: [Feature Request] Addition of Leetcode Platform Problems Solutions
### Is your feature request related to a problem? Please describe.
Yes, I want to add Leetcode Problems Solutions in depth.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Shariq2003**
### Description
I have added leetcode solution of 1-10 questions.
image

Fixes #173 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — APPROVED** [review]
ok

**Comment by NEGRAH-S** [comment]
@MastanSayyad Kindly check documentation change here Level 1 shall be given.

**Comment by MastanSayyad** [comment]
@NEGRAH-S Yes do level 1

**Comment by NEGRAH-S** [comment]
@ajay-dhangar kindly change and see if any other are also there, change them as well to Level 1

**Pull request merged**
