### PR TITLE
Update search-BST.md

### LINKED ISSUE #1295: [Feature]: add java code in bst search
### Feature Name

add java code in bst deletion

### Feature Description

use full for java

### Motivation

not found

### Implementation Suggestions (Optional)

_No response_

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [X] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

### References (Optional)

_No response_

### PR DESCRIPTION
**Pull request by nishant4500**
### Description
add java code

Fixes #1295 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by nishant4500** [comment]
label plz @ajay-dhangar

**Comment by nishant4500** [comment]
@ajay-dhangar

**Comment by nishant4500** [comment]
hello @ajay-dhangar can you please label it level or gssoc-ext for the points

**Comment by nishant4500** [comment]
@ajay-dhangar can you please label it since it helps me to gain points as Gssoc near to end

**Comment by Meetjain1** [comment]
@ajay-dhangar Please add respective labels on this pr asap and dont forget to add labels on any pr , it creates confusion among contributors that their pr points are not showing up on the leaderboard.

Core Team 
Gssoc-ext

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar Please add respective labels on this pr asap and dont forget to add labels on any pr , it creates confusion among contributors that their pr points are not showing up on the leaderboard.
> 
> Core Team Gssoc-ext

Sure

**Comment by Meetjain1** [comment]
> > @ajay-dhangar Please add respective labels on this pr asap and dont forget to add labels on any pr , it creates confusion among contributors that their pr points are not showing up on the leaderboard.
> > 
> > Core Team Gssoc-ext
> 
> Sure

Thankyou for your response @ajay-dhangar

**Pull request merged**
