### PR TITLE
Added B-Tree Operations: Introduction, Insertion, and Deletion Documentation

### LINKED ISSUE #463: [Feature Request] Add B-tree Section in the docs
### Is your feature request related to a problem? Please describe.
yes! B-tree is a very important part of data structure and algorithms

### Describe the solution you'd like

The docs will contain:

- [x] Introduction of B-Tree
- [x] Insert Operation in B-Tree
- [x] Delete Operation in B-Tree

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Description
B-Tree Operations: Introduction, Insertion, and Deletion Documentation

- Closes : #463 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by IkkiOcean** [comment]
it says cant find variable n, but I have only added .md files and images.
can you help me? @ajay-dhangar

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
recheck your `B-Tree-1.md` file and solve error

**Comment by IkkiOcean** [comment]
Screenshot 2024-10-16 at 3 55 08 PM

Done! please merge it soon @ajay-dhangar

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
