### PR TITLE
Created introduction to Strings and String builders.md

### PR DESCRIPTION
**Pull request by kaishwarya24**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please read our contribution guidelines carefully. We have already shared all of our resources, including syntax and format guidelines. Please update your code to match our guidelines.

**Comment by kaishwarya24** [comment]
I will make it according to guidelines sorry for inconvenience

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
What is this syntax you need to follow.md? Is it markdown or html? If it's markdown, how do I convert it to html?

**Comment by kaishwarya24** [comment]
I used html

**Comment by ajay-dhangar** [comment]
> I used html

My mean you need used only markdown syntax not HTML and follow our formate

**Comment by kaishwarya24** [comment]
i couldn't find the format rules can you help me find them so i can complete it properly this time

**Comment by ajay-dhangar** [comment]
> i couldn't find the format rules can you help me find them so i can complete it properly this time

careful read our https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md

**Pull request closed without merging**
