### PR TITLE
Add 3D-Array to the Repo.

### LINKED ISSUE #907: Add 3D array to the repo.
hey i would like to add add 3D array to the repository .
allow me to contribute.

### PR DESCRIPTION
**Pull request by harshbhardwaj000**
### Description
as this repository work to collect information of different different algos so as a contributor i suppose to add 3D-array to the repository.

Fixes #907 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
why you add `.github/workflows/jekyll-gh-pages.yml` can you delete

**Comment by harshbhardwaj000** [comment]
sorry i mistakenly add it.
i will remove it

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
The content you need to write is in the `docs` folder, not outside of the `docs` folder. For example, `docs/arrays/3D-Array.md`.

**Comment by harshbhardwaj000** [comment]
but docs does not have any folder name as arrays.

**Comment by harshbhardwaj000** [comment]
done. **docs/basic-dsa/array/3D-Array.md**

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
You need to follow careful .md syntax because you are backed by some rules. If you don't follow the rules, your changes won't be accepted.

**Pull request closed without merging**
