### PR TITLE
Implementation of Heap  tree algorithm

### LINKED ISSUE #497: [Feature Request] Heap Tree Implementation
### Is your feature request related to a problem? Please describe.
The current repository lacks an implementation and documentation for Heap Trees, which are fundamental data structures used in various applications such as priority queues and heap sort. This absence makes it difficult for learners to gain a comprehensive understanding of tree-based data structures and their practical applications.

### Describe the solution you'd like

To address the absence of Heap Trees, I propose adding a detailed section that includes:

Introduction: Explanation of Min Heap and Max Heap, and their differences.
Heap Operations: Insertion, Deletion, Heapify, Extract-Min/Extract-Max.
Implementation: Code examples in TypeScript and JavaScript with step-by-step explanations.
Applications: Use cases like Priority Queues and Heap Sort Algorithm.

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Subashree-selvaraj**
### Description
This change adds the heap tree algorithm to the repository, which is essential for various applications in data structures and algorithms.

Fixes #497 

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Subashree-selvaraj** [comment]
@ajay-dhangar Raised PR kindly check it !

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar Raised PR kindly check it !

This branch has conflicts that must be resolved. Please use the command line to resolve the conflicts before continuing. The conflicting files are listed below.

**Comment by Subashree-selvaraj** [comment]
@ajay-dhangar Resolved conflicts kindly check it!
fixes #497

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
