### PR TITLE
Implementing Python Datatypes

### LINKED ISSUE #80: [Feature Request] Imnplementing Python Tutorials
## 🚀 Implementing Python programming tutorials

###This website currently don't have Python programming tutorials 

### I want to implement Python programming tutorials

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Soumya03007**
### Description
Added Python Datatypes
Fixes #142

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Can you modify this to make it easier to understand? For example, can you write some details about the implementation?

**Comment by Soumya03007** [comment]
yess , but implementation details means what things i need to include pls mention this

**Review by Soumya03007 — COMMENTED** [review]
I have added the changes requested

**Review by ajay-dhangar — APPROVED** [review]
done

**Pull request merged**
