### PR TITLE
 Minimum Window Substring to Top DSA interview questions (Issue #1647)

### LINKED ISSUE #1647: [Custom]: <ADD A PROBLEM> Minimum Window Substring to Top DSA interview questions
### Issue Summary

Minimum Window Substring

### Issue Description

 Minimum Window Substring to Top DSA interview questions

### Proposed Solution (Optional)

_No response_

### Priority

High - Requires urgent attention

### Category

- [X] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

### Additional Context (Optional)

_No response_

### PR DESCRIPTION
**Pull request by shriyadindi**
### Description
 Minimum Window Substring to Top DSA interview questions.

Fixes #1647

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ajay-dhangar** [comment]
This branch has conflicts that must be resolved. Please use the web editor or the command line to resolve the conflicts.

**Comment by shriyadindi** [comment]
@ajay-dhangar Resolved the conflicts

**Comment by shriyadindi** [comment]
5 PRs merged but label not assigned.
https://github.com/ajay-dhangar/algo/pull/1641
https://github.com/ajay-dhangar/algo/pull/1625
https://github.com/ajay-dhangar/algo/pull/1626
https://github.com/ajay-dhangar/algo/pull/1627
https://github.com/ajay-dhangar/algo/pull/1643

**Review by ajay-dhangar — APPROVED** [review]
👍

**Pull request merged**
