### PR TITLE
Added Towers of Hanoi in Recursion

### LINKED ISSUE #349: add towerofhanoi recursive algo
ad towerofhanoi recursive algo

### PR DESCRIPTION
**Pull request by Lokesh11868**
### Description
I have Added Towers of Hanoi topic in Recursion Section. 

Fixes #349

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✓] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Lokesh11868** [comment]
I request labeling of the issue as hacktoberfest-accepted, gssoc'24 ext and with suitable level
Thank you!

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
why your are added code in `package-lock.json` file can you explain

**Comment by Lokesh11868** [comment]
> why your are added code in `package-lock.json` file can you explain

Sure,
image

"license": "MIT" entry was added automatically by npm when I installed the dependencies this happens because npm records the license information for each package the change is part of npm's normal operation for managing dependencies and recording license details.

**Comment by ajay-dhangar** [comment]
> > why your are added code in `package-lock.json` file can you explain
> 
> Sure, image
> 
> "license": "MIT" entry was added automatically by npm when I installed the dependencies this happens because npm records the license information for each package the change is part of npm's normal operation for managing dependencies and recording license details.

delete line number `2382` and `2713`

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
