### PR TITLE
Includes Sorting Visualizer for All Sorting Algorithm

### LINKED ISSUE #1286: [Feature]: Add Visualization of All sorting algorithms
### Feature Name

Add Visualization of All sorting algorithms 

### Feature Description

Add Visualization of All sorting algorithms so that we can understand easly whats happening and how the algo is work..

### Motivation

we can understand easly whats happening and how the algo is work..

### Implementation Suggestions (Optional)

_No response_

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [ ] Additional Documentation
- [ ] Third-Party Libraries
- [X] UI/UX Design
- [ ] Other

### References (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Meetpidev**
### Description
Added Sorting Visualizer for All Sorting Algorithm

Fixes #1286 

### Type of change
- New feature (non-breaking change which adds functionality)

- [ Yes ] My code follows the style guidelines of this project
- [ Yes ] I have performed a self-review of my code
- [ Yes ] I have commented my code, particularly in hard-to-understand areas
- [ Yes ] I have added tests that prove my fix is effective or that my feature works
- [ Yes ] New and existing unit tests pass locally with my changes
- [ Yes ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Meetpidev** [comment]
@ajay-dhangar Please Review PR....

**Comment by Meetpidev** [comment]
@ajay-dhangar Please Review It...

**Comment by Meetpidev** [comment]
@ajay-dhangar Review PR... Please...

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
not a good practice and cannot make complexity for us,

**Pull request closed without merging**
