### PR TITLE
Stone Paper Scissor Via Recusrion

### LINKED ISSUE #1547: [Feature]: Stone paper Scissor Game Via Recursion
### Feature Name

Stone paper Scissor Game Via Recursion 

### Feature Description

The Stone-Paper-Scissors game is a two-player game where each player chooses between Stone (Rock), Paper, or Scissors in a quick showdown. Each move has a unique interaction:

Stone crushes Scissors.
Scissors cut Paper.
Paper covers Stone.
The game typically includes:

Round-Based Play: The game is played over multiple rounds, with each round’s winner earning a point.
Score Tracking: Scores are updated after each round, and the player with the most points at the end wins.
Draw Handling: If both players choose the same move, the round ends in a draw without points.
Strategic Elements: While luck plays a role, players can anticipate and counter opponents’ patterns. This blend of chance and strategy makes Stone-Paper-Scissors a simple yet engaging game.

### Motivation

Adding the Stone-Paper-Scissors game to Algo enhances the platform with an interactive and fun feature that users can enjoy during breaks from more intensive algorithmic or problem-solving tasks. Here’s why this feature would be beneficial:

User Engagement: Stone-Paper-Scissors is simple, familiar, and quick to play. It adds a lighthearted element that can improve user engagement, especially for those who enjoy short, casual games.

Cognitive Break: The game provides a mental reset for users engaged in complex problem-solving tasks. This helps prevent burnout and keeps users fresh and ready for continued learning or coding challenges.

Strategy and Prediction: Stone-Paper-Scissors incorporates elements of strategy and prediction, allowing users to apply skills like pattern recognition in a casual setting, aligning with Algo’s focus on strategic thinking.

Community Interaction: If implemented with multiplayer support or leaderboards, the game could foster friendly competition within the Algo community, building camaraderie and user loyalty.

### Implementation Suggestions (Optional)

_No response_

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [X] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

### References (Optional)

_No response_

### PR DESCRIPTION
**Pull request by MithanshuHedau**
## 📥 Pull Request

issue  #1547 

### Description
The Stone-Paper-Scissors Game is a classic hand game that involves two players making simultaneous choices between three options: Stone (Rock), Paper, and Scissors. Each option has specific interactions that determine the outcome: Stone crushes Scissors, Scissors cut Paper, and Paper covers Stone. This simple yet strategic game is not only fun but also a quick way to settle disputes or make decisions.

In the digital version of the game, players can compete against a computer opponent or each other. The game features an intuitive interface for selecting moves, real-time feedback on the outcomes of each round, and score tracking to determine the overall winner after multiple rounds. The combination of chance and psychology makes it an engaging experience, as players attempt to predict their opponent's moves while strategically choosing their own.

With its straightforward rules and fast-paced nature, the Stone-Paper-Scissors Game appeals to players of all ages. It's an excellent way to develop quick thinking and decision-making skills while enjoying friendly competition. Whether played casually or as part of a larger game night, the game remains a timeless favorite that fosters interaction and fun.

Fixes  #1547 

### Type of change

- [ ✅] New feature (non-breaking change which adds functionality)
- [✅ ] Documentation update

### Checklist:

- [ ✅] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my code
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [✅ ] New and existing unit tests pass locally with my changes
- [ ✅] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Write your description in sort words in string format

**Comment by MithanshuHedau** [comment]
@ajay-dhangar , Please check it  now ; if is all okay or not

**Comment by MithanshuHedau** [comment]
@ajay-dhangar , any Update please ?

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
