### PR TITLE
Added-easy-array-10-leetcode-problems-solutions

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please close this pull request. We already have a repository with solutions to all LeetCode problems. You can find it at https://codeharborhub.github.io/dsa/solutions/category/leetcode-solutions

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
thank you sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
level didnt get changed sir

**Pull request merged**
