### PR TITLE
Create Divide-and-Conquer.md

### PR DESCRIPTION
**Pull request by Bhumika-00**
Added the divide and conquer algo

### Description
Ihave added divide and conquer algo as b een sugested inside arrays.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Bhumika-00** [comment]
I have completed the PR

**Comment by Bhumika-00** [comment]
Thanks a lot

**Comment by Bhumika-00** [comment]
I have done one more pr for searching algo please review it

**Pull request merged**
