### PR TITLE
Added heapsort.cpp

### LINKED ISSUE #774: Add Heap Sort in cpp
### Is your feature request related to a problem? Please describe.
A heap sort code may be added in the list.

### Describe the solution you'd like
I want to code the solution in cpp.

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KashishJuneja101003**
### Description
The code for heap sort in cpp along with algo is pasted.

Fixes #774 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
We need to write code only in .md files for our docs. Therefore, please delete the .cpp file and write your code in a .md file.

**Comment by KashishJuneja101003** [comment]
Kindly review the PR.
Thank You!

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by KashishJuneja101003** [comment]
Hello,
Could you please add hacktoberfest-accepted label?
Thank you!

**Pull request merged**
