### PR TITLE
Create pointer

### LINKED ISSUE #202: [Feature Request] Added references vs pointers
## 🚀 Feature Request
List of the contents for "References vs Pointers in C++":

What are References and Pointers in C++?
Declaring References and Pointers
Declaring References
Declaring Pointers
Differences Between References and Pointers
Syntax and Usage
Initialization
Reassignment
Null Values
Memory Address
When to Use References and Pointers
Use References
Use Pointers
Examples
Example 1: Using References
Example 2: Using Pointers
Conclusion

## 1. What are References and Pointers in C++?

In C++, both references and pointers are used to refer to memory locations, but they have different properties and uses. 

- **References**: An alias for another variable.
- **Pointers**: A variable that holds the memory address of another variable.

References vs Pointers in C++

### Declaring References

A reference is declared using the `&` operator.

**Syntax:**

```cpp
datatype &referenceName = variableName;
```

**Example:**

```cpp
#include <iostream>
using namespace std;

int main() {
    int a = 10;
    int &ref = a;  // ref is a reference to a
    cout << "a: " << a << endl;    // Output: 10
    cout << "ref: " << ref << endl;  // Output: 10
    return 0;
}
```

### Declaring Pointers

A pointer is declared using the `*` operator.

**Syntax:**

```cpp
datatype *pointerName;
```

**Example:**

```cpp
#include <iostream>
using namespace std;

int main() {
    int a = 10;
    int *ptr = &a;  // ptr holds the address of a
    cout << "a: " << a << endl;      // Output: 10
    cout << "ptr: " << ptr << endl;  // Output: address of a
    cout << "*ptr: " << *ptr << endl;  // Output: 10
    return 0;
}
```

### 1. Syntax and Usage

- **References**: Use the `&` operator for declaration and do not require dereferencing.
- **Pointers**: Use the `*` operator for declaration and require dereferencing with `*`.

**Example:**

```cpp
int a = 5;
int &ref = a;  // Reference
int *ptr = &a;  // Pointer
```

### 2. Initialization

- **References**: Must be initialized when declared.
- **Pointers**: Can be declared without initialization and assigned later.

**Example:**

```cpp
int a = 5;
int &ref = a;  // Must be initialized
int *ptr;     // Can be declared without initialization
ptr = &a;     // Assigned later
```

### 3. Reassignment

- **References**: Cannot be reassigned to refer to another variable.
- **Pointers**: Can be reassigned to point to different variables.

**Example:**

```cpp
int a = 5, b = 10;
int &ref = a;  // Reference to a
// ref = b;   // Error: Cannot reassign a reference

int *ptr = &a;  // Pointer to a
ptr = &b;       // Pointer reassigned to b
```

### 4. Null Values

- **References**: Cannot be null.
- **Pointers**: Can be null (useful to indicate that they are not pointing to any valid memory).

**Example:**

```cpp
int a = 5;
int &ref = a;  // Reference cannot be null

int *ptr = nullptr;  // Pointer can be null
ptr = &a;            // Pointer assigned to a valid address
```

### 5. Memory Address

- **References**: Implicitly provide the memory address of the referenced variable.
- **Pointers**: Explicitly hold and can be used to manipulate memory addresses.

**Example:**

```cpp
int a = 5;
int &ref = a;  // Reference to a
int *ptr = &a; // Pointer to a

cout << "Address of a: " << &a << endl;
cout << "Address using ref: " << &ref << endl;
cout << "Address using ptr: " << ptr << endl;
```

### Use References:
- When you need an alias for another variable.
- When you want to avoid null checks and pointer arithmetic.
- For pass-by-reference in function arguments to avoid copying large objects.

### Use Pointers:
- When you need to allocate memory dynamically.
- When you need to implement data structures like linked lists, trees, etc.
- When you need to use null values to indicate "no object".

### Example 1: Using References

```cpp
#include <iostream>
using namespace std;

void increment(int &ref) {
    ref++;
}

int main() {
    int a = 10;
    increment(a);
    cout << "a: " << a << endl;  // Output: 11
    return 0;
}
```
### Example 2: Using Pointers
```cpp
#include <iostream>
using namespace std;
void increment(int *ptr) {
    (*ptr)++;
}
int main() {
    int a = 10;
    increment(&a);
    cout << "a: " << a << endl;  // Output: 11
    return 0;
}
```

## 6. Conclusion

Both references and pointers are powerful features in C++ that allow you to manipulate memory and create more efficient programs. Understanding the differences between them and knowing when to use each is crucial for effective C++ programming

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by nishant4500**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #202 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nishant4500** [comment]
@ajay-dhangar please look in to this

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
We need a `.md` file for our docs. I suggest using `docs/basic-dsa/pointer.md`. Please let me know if you have any objections.

**Comment by nishant4500** [comment]
@ajay-dhangar could please look into this I made the changes

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
