### PR TITLE
Added oops in c++

### LINKED ISSUE #1231: [Alogorith]: < Implement Object-Oriented Programming (OOP) Concepts in C++>
# OOPS IN C++

## Feature Description

The feature involves adding a comprehensive implementation of Object-Oriented Programming (OOP) concepts in C++ within the algorithm repository. This implementation will include a series of code examples and explanations that demonstrate the fundamental principles of OOP, allowing users to learn how to leverage these concepts effectively in their programming projects.

Key Components of the Feature:

Classes and Objects:

Description: A class serves as a blueprint for creating objects, encapsulating data for the object and methods to manipulate that data.
Example: A class Car might have attributes like make, model, and year, along with methods like start() and stop().
Benefit: This encapsulation allows for organized and modular code, making it easier to manage complex systems.
Encapsulation:

Description: Encapsulation restricts direct access to some of an object's components, which can prevent the accidental modification of data. It is achieved through access specifiers (public, private, protected).
Example: Using private access for sensitive attributes in a BankAccount class ensures that they can only be modified through specific methods, like deposit() or withdraw().
Benefit: This improves data integrity and security, promoting better software design practices.
Inheritance:

Description: Inheritance allows a class (derived class) to inherit attributes and methods from another class (base class), facilitating code reusability.
Example: A class ElectricCar can inherit from Car, adding attributes specific to electric vehicles, such as batteryCapacity.
Benefit: This reduces code duplication and makes it easier to create specialized classes that build upon existing functionality.
Polymorphism:

Description: Polymorphism enables methods to do different things based on the object that it is acting upon. It includes method overloading (compile-time) and method overriding (runtime).
Example: A method display() in a base class can be overridden in derived classes (Car, Truck, etc.) to provide class-specific behavior.
Benefit: This flexibility allows for the implementation of dynamic behavior, making code more adaptable and extensible.
Abstraction:

Description: Abstraction involves hiding complex implementation details and showing only the essential features of the object. This is typically achieved using abstract classes and interfaces.
Example: An abstract class Shape can define a method draw(), which must be implemented by derived classes like Circle and Square.
Benefit: This promotes cleaner interfaces and a clearer separation between implementation and interface, making code easier to understand and maintain.

## Motivation

Many algorithms and data structures are best understood through the lens of OOP. Adding OOP examples allows users to see how these concepts can be applied in a real-world context, bridging the gap between theory and practice. This practical application helps reinforce the learning of both algorithms and OOP.

## Documentation and Tutorials:

Write detailed documentation and tutorials explaining each OOP concept. Include code snippets and comments to enhance understanding. Use Markdown files for clarity.

## Leverage Libraries:

Utilize C++ libraries that support OOP concepts. For instance:
Boost: Provides extensive libraries that facilitate OOP implementations.
Qt: A framework for building GUI applications that employs OOP principles extensively.

### Does this feature require additional resources?

- [X] Additional Documentation
- [ ] Third-Party Libraries
- [ ] UI/UX Design
- [ ] Other

### References (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Riya7045**
### Description
 Implementation of Object-Oriented Programming (OOP) concepts in C++ .This implementation will include a series of code examples and explanations that demonstrate the fundamental principles of OOP, allowing users to learn how to leverage these concepts effectively in their programming projects.

Fixes #1231 

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please read our contribution guidelines carefully. We only accept .md files, not other formats.

**Comment by Riya7045** [comment]
ohkay i will do the necessary changes

**Comment by Riya7045** [comment]
please check it once now

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please read the `.md` (markdown) format/syntax carefully. Also, check out our documentation format and write your code based on our format.

**Pull request closed without merging**
