### PR TITLE
Added 5 Array&String Question Solution in cpp

### LINKED ISSUE #453: [General] LeetCode 75 Qs
The solution to the questions in Ace Coding Interview with 75 Qs in LeetCode

### PR DESCRIPTION
**Pull request by aditiverma-21**
### Description
first 5 Ace Coding Interview with 75 Qs in LEETCODE with c++ solutions 

Fixes #453

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
We need only .md files for our docs, so please delete all .cpp files and write all concepts in .md files.

**Comment by aditiverma-21** [comment]
@ajay-dhangar okay thank you .

**Comment by aditiverma-21** [comment]
should I create new PR or just edit in this one?

**Comment by aditiverma-21** [comment]
@ajay-dhangar I will be new PR for the same.

**Pull request closed without merging**
