### PR TITLE
Add Documentation: Algorithm Optimization Techniquesscroll to up butt…

### LINKED ISSUE #51: Documentation: Algorithm Optimization Techniques
Techniques such as Dynamic Programming optimizations, Bit Manipulation Tricks, or Space Optimization Techniques that can help improve the efficiency of the algorithms.
I want to add a dedicate .md file for this 
Hey @ajay-dhangar  please assign me this task

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Have written document as in .md file in which i have defined techniques such as Dynamic Programming optimizations, Bit Manipulation Tricks, or Space Optimization Techniques that can help improve the efficiency of the algorithms.
Hey @ajay-dhangar please approve my PR

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

**Comment by shubhagarwal1** [comment]
have made requested changes please review the changes

**Review by ajay-dhangar — APPROVED** [review]
💖

**Comment by NEGRAH-S** [comment]
@MastanSayyad kindly look as documentation changes shall come under Level 1

**Comment by MastanSayyad** [comment]
@NEGRAH-S Yes

**Comment by NEGRAH-S** [comment]
@ajay-dhangar , Change this to Level 1 And see if any other have same cahnges make them level 1 as well

**Review by MastanSayyad — COMMENTED** [review]
Hi @ajay-dhangar add level 1 label to this PR 

readme = level 1 (no matter how many number of changes)

also add me as a collaborator

**Pull request merged**
