### PR TITLE
solved #478 #647 #649

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes 
- [x] #478 
- [x] #647 
- [x] #649

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
created challenege 1 and avl tree quiz in challenge i added the timer too consider as level3

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
challenge-1-1

challenge-1-2
challenge1-result
kindly consider as level3

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please merge this

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please consider this as level 3 and  i have made changes

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
