### PR TITLE
Added feedback option

### LINKED ISSUE #206: Add feedback option
## 🚀 Feature Request
Add feedback option
image
either at top or bottom
assign this to me under gssoc ext and hacktoberfest

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Aditijainnn**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Added feedback option

https://github.com/user-attachments/assets/ccbbd6b9-96a5-4d28-9cb4-ba5713b159ed

Fixes #206

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Thank you for your contribution! We already have this feature available [here](https://ajay-dhangar.github.io/algo/docs/#get-started-with-algo). If you would like to integrate it into the documentation, please use `<GiscusComponent />`. For other pages, such as the homepage, you can import and use it as shown below:

```tsx
import GiscusComponent from "@site/src/components/GiscusComponent";
...

<GiscusComponent />
```

This approach will help keep the codebase clean and consistent. Let me know if you have any questions!

**Comment by Aditijainnn** [comment]
> Thank you for your contribution! We already have this feature available [here](https://ajay-dhangar.github.io/algo/docs/#get-started-with-algo). If you would like to integrate it into the documentation, please use `<GiscusComponent />`. For other pages, such as the homepage, you can import and use it as shown below:
> 
> ```tsx
> import GiscusComponent from "@site/src/components/GiscusComponent";
> ...
> 
> <GiscusComponent />
> ```
> 
> This approach will help keep the codebase clean and consistent. Let me know if you have any questions!

Ok made all changes as youu said
image
when we click on feedback button this will opens up

**Comment by Aditijainnn** [comment]
> > Thank you for your contribution! We already have this feature available [here](https://ajay-dhangar.github.io/algo/docs/#get-started-with-algo). If you would like to integrate it into the documentation, please use `<GiscusComponent />`. For other pages, such as the homepage, you can import and use it as shown below:
> > ```tsx
> > import GiscusComponent from "@site/src/components/GiscusComponent";
> > ...
> > 
> > <GiscusComponent />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This approach will help keep the codebase clean and consistent. Let me know if you have any questions!
> 
> Ok made all changes as youu said image when we click on feedback button this will opens up

@ajay-dhangar you can review it

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Why was feedback added to the footer? This is not considered good practice.

**Comment by Aditijainnn** [comment]
> Why was feedback added to the footer? This is not considered good practice.

can you explain in what form you want

**Comment by ajay-dhangar** [comment]
I don't think we need a form right now. You can work on other things for the time being. Once we connect Algo to our back end, we can create a form, but it's not necessary at this time.

**Pull request closed without merging**
