### PR TITLE
[Feature Request] Linked Lists

### LINKED ISSUE #91: [Feature Request] Linked Lists
### Is your feature request related to a problem? Please describe.
I often find myself needing to manage collections of data that can grow and shrink dynamically. Linked lists are a fundamental data structure that allows for efficient insertion and deletion of elements. Unlike arrays, linked lists do not require contiguous memory allocation, making them more suitable for dynamic datasets that frequently change in size. Linked Lists can help manage big collection of data very easily.

### Describe the solution you'd like
I would like to implement a linked list data structure that supports the following operations:

- Insertion: Add elements at the head, tail, or at a specific position in the list.
- Deletion: Remove elements by value or position, allowing for easy management of the dataset.
- Traversal: Traverse the linked list to display its contents, facilitating better visualization of the data.
- Searching: Implement a search function to find specific elements within the list.

### Describe alternatives you've considered
I considered using arrays or dynamic arrays; however, they do not provide efficient insertion and deletion capabilities, especially when dealing with large datasets or frequent updates.

### Additional context
Implementing linked lists will help us tackle various problems more efficiently, such as managing user inputs, processing queues, or implementing stacks.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by AnujSaha0111**
### Description
Linked lists are a fundamental data structure that allows for efficient insertion and deletion of elements. Unlike arrays, linked lists do not require contiguous memory allocation, making them more suitable for dynamic datasets that frequently change in size. Linked Lists can help manage big collection of data very easily.

Fixes #91 

### Type of change

- [x] New feature (non-breaking change which adds functionality) - LinkedList

### Checklist:

Insertion: Add elements at the head, tail, or at a specific position in the list. 
Deletion: Remove elements by value or position, allowing for easy management of the dataset. 
Traversal: Traverse the linked list to display its contents, facilitating better visualization of the data. 
Searching: Implement a search function to find specific elements within the list. 
There are also implementation of Circular LinkedList and Doubly LinkedList

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
delete `.java` files and write your code in `.md` file

**Comment by AnujSaha0111** [comment]
> delete `.java` files and write your code in `.md` file

Done with the changes

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please carefully review our documentation structure before you start writing code. The documentation doesn't follow our structure, so you'll need to make changes to the documentation.

**Comment by shalini-bhandari** [comment]
@ajay-dhangar I already created this issue #53 and it was completed as well. Kindly look into it.

**Pull request closed without merging**
