### PR TITLE
Added visualization tool for Heap Sort, AVL Trees and Graph Coloring

### LINKED ISSUE #574: Algorithm Exploration: AVL Trees, Heap Sort, and Graph Coloring Visualized
Title: Algorithm Exploration: AVL Trees, Heap Sort, and Graph Coloring Visualized

Description:
I would like to add  "Algorithm Exploration: AVL Trees, Heap Sort, and Graph Coloring Visualized," as an educational tool to the project. This tool offers interactive visualizations of fundamental algorithms and data structures, which can significantly enhance users’ understanding of algorithmic concepts.
AVL Tree Visualizer: Demonstrates real-time operations such as insertions, deletions, and rebalancing through animated visualizations. It helps users grasp the complexity of tree balancing.
Heap Sort Visualizer: This JavaScript-based tool allows users to input arrays and see each step of the Heap Sort algorithm in action, enhancing understanding of sorting mechanisms.
Graph Coloring Visualizer: A Python-based tool that illustrates different graph coloring algorithms, providing an interactive way to explore graph theory concepts.

### PR DESCRIPTION
**Pull request by greeshma275**
Title:  Visualization tool for Heap Sort, AVL Trees and Graph Coloring

Fixes https://github.com/ajay-dhangar/algo/issues/574

The visualization tool provides interactive and animated visualizations for three fundamental algorithms: Heap Sort, AVL Trees, and Graph Coloring. It demonstrates real-time steps of Heap Sort, showcasing heap construction and sorting. The AVL Tree visualizer shows insertions, deletions, and self-balancing operations through dynamic animations. The Graph Coloring tool illustrates various coloring algorithms, helping users understand vertex coloring and conflict minimization. Each visualizer offers intuitive controls and clear representations, making algorithm learning more engaging.
I have added this tool to the project.

### CODE REVIEW

**Comment by ajay-dhangar** [comment]
@greeshma275 can you share issues number

**Comment by greeshma275** [comment]
#574

**Comment by greeshma275** [comment]
@ajay-dhangar  issue number is #574

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
You need to write your logic in JSX or TSX, and your documentation in Markdown or MDX. Please read our contribution guidelines carefully; they provide all the information you need.

**Pull request closed without merging**
