### PR TITLE
added some questions 

### LINKED ISSUE #709: [Feature Request] adding search insert position question
### Is your feature request related to a problem? Please describe.
i want to add search insert position question of leetcode
assign this issue to me pls

---

**Would you like to work on this feature?**  
- [ yes] Yes  
- [ ] No

### LINKED ISSUE #711: [Feature Request] adding remove element question
### Is your feature request related to a problem? Please describe.
i want to add remove element question of leetcode.
assign this issue to me pls

---

**Would you like to work on this feature?**  
- [ yes] Yes  
- [ ] No

### LINKED ISSUE #712: [Feature Request] adding first missing positive question
### Is your feature request related to a problem? Please describe.
i want to add first missing positive question on leetcode.
assign this issue to me pls

---

**Would you like to work on this feature?**  
- [ yes] Yes  
- [ ] No

### LINKED ISSUE #713: [Feature Request] adding pow(x,n) question
### Is your feature request related to a problem? Please describe.
i want to add pow(x,n) question of leetcode.
assign this issue to me pls

---

**Would you like to work on this feature?**  
- [ yes] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Abhishek2634**
### Description
@ajay-dhangar   i have added 4 leetcode question have a look on that. 
 
Fixes # (#668) #669 #670 #671

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Abhishek2634** [comment]
@ajay-dhangar bro can you merge the PR ?

**Comment by Abhishek2634** [comment]
@ajay-dhangar solve issue no. #709  #711 #712  #713.

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Abhishek2634** [comment]
Thanks @ajay-dhangar  close these as well  #668 #669 #670 #671 these issues are also linked with this PR.

**Pull request merged**
