### PR TITLE
MR Conflict Resolved for PR #1171

### LINKED ISSUE #1155: [bug] breaking issue in knapsack page
check attachment

Screenshot 2024-10-21 221502

assign me this under hacktoberfest and gssoc-ext

### PR DESCRIPTION
**Pull request by AE-Hertz**
### Description
fix fractional knapsack code issue

Fixes #1155 

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AE-Hertz** [comment]
@ajay-dhangar MR conflict resolved for PR no. #1171

**Comment by AE-Hertz** [comment]
@ajay-dhangar sir can you merge my PRs and please assign me my new issues. thank you

**Comment by AE-Hertz** [comment]
@ajay-dhangar hoping to get my PR merged

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
