### PR TITLE
hashtable.md

### LINKED ISSUE #1229: [Feature]: Add java and cpp code in hashTable
### Feature Name

Add  java  and Cpp code

### Feature Description

HashTable adding java as well as cpp code 

### Motivation

I can enhance some features

### Implementation Suggestions (Optional)

_No response_

### Feature Type

New Algorithm

### Does this feature require additional resources?

- [X] Additional Documentation
- [X] Third-Party Libraries
- [X] UI/UX Design
- [ ] Other

### References (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Aasthaa10**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1229

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ .] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ .] Documentation update

### Checklist:

- [ .] My code follows the style guidelines of this project
- [ .] I have performed a self-review of my code
- [ .] I have commented my code, particularly in hard-to-understand areas
- [ .] I have added tests that prove my fix is effective or that my feature works
- [ .] New and existing unit tests pass locally with my changes
- [ .] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Docs/Hashing/.md is not a good file name. Can you write a better name?

**Comment by Aasthaa10** [comment]
sure i can modify it

**Comment by Aasthaa10** [comment]
Can you merge itt

**Comment by Aasthaa10** [comment]
please merge the pr @ajay-dhangar

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
