### PR TITLE
 aded odd even sort

### LINKED ISSUE #305: [Feature Request] <odd even sort>
🚀 Feature Request: Implement Odd-Even Sort
Is your feature request related to a problem? Please describe.
I’m frustrated when sorting algorithms like bubble sort or insertion sort are used in our application because they can be inefficient for larger datasets. The need for an efficient, parallelizable sorting algorithm is evident, especially when dealing with large arrays. An odd-even sort could provide a simple yet effective solution.

Describe the solution you'd like
I would like to implement the Odd-Even Sort algorithm in our project. This algorithm works by repeatedly comparing adjacent elements in the array. The sorting is done in two phases:

Odd Phase: Compare elements at odd and even indices, swapping them if they are out of order.
Even Phase: Compare elements at even and odd indices, swapping them if they are out of order.
This process is repeated until no swaps are needed, indicating that the array is sorted.

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by priyashuu**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #305

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
-

### CODE REVIEW

**Comment by priyashuu** [comment]
image

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
I'd like to update the code in your `docs/algorithms/sorting-algorithms/OddEvenSort.md` file. The code is not formatted to match our documentation syntax, so I'd like you to rewrite it.

**Comment by priyashuu** [comment]
done

**Comment by priyashuu** [comment]
done

**Comment by priyashuu** [comment]
image

**Review by ajay-dhangar — APPROVED** [review]
done

**Pull request merged**
