### PR TITLE
UI Enhancement in ContactUs

### LINKED ISSUE #687: [Feature Request] <UI ENhancement in Contact Us Section>
### Is your feature request related to a problem? Please describe.
The UI is not good. It is very basic

### Describe the solution you'd like
I can use combination of colors that align well with the website theme and add flex properties to put form one side and contact info on other.
Different properties can be used to make it look better an attractive.

image

### Additional context
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Bhum-ika**
### Description
I have successfully edited the contactUs Section by changing its alignment, bg color and more.

Fixes #687 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

Screenshot 2024-10-16 012644
Screenshot 2024-10-16 012705

### CODE REVIEW

**Comment by Bhum-ika** [comment]
Hi @ajay-dhangar 
I hope you like it. I have made sure it is responsive.
I **would really appreciate if you could attach level3 bage along with gssoc-ext n hactoberfest-accepted badges.**
Look forward to contribute more!!

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please don't edit the `package-lock.json` file. If you do, you won't be able to fix or push your PR.

**Comment by Bhum-ika** [comment]
Okay I'll fix this and push the changes

**Comment by Bhum-ika** [comment]
Please check and let me know, if there is still any error

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
I think there is something wrong in your `package-lock.json` file. My suggestion is that you first save your feature's code in a safe place on your machine. Then delete your code and sync the latest main branch code. Make sure you don't edit `package.json` and `package-lock.json`, because this can be dangerous for our setup. If you need to add any packages or dependencies, please share them with us so we can better understand your changes.

**Pull request closed without merging**
