### PR TITLE
solved #736

### LINKED ISSUE #736: [Feature Request] <Title of your feature>add solutions to quiz on queues
### Is your feature request related to a problem? Please describe.
add solutions to quiz on queues
### Describe the solution you'd like
add solutions to quiz on queues
### Describe alternatives you've considered
add solutions to quiz on queues
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
solved #736
Fixes #736 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please merge  ths pull request

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please merge this

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sir please update the level sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sir only 10 points were added for the 7 commits and adding 7 quiz solutions
sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir only 10 points were alloted please change level

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
arraysol
bintree
bst
btreesol1
btreesol2
quizsol1
quizsol2
redblack

**Pull request merged**
