### PR TITLE
loops&decisionmaking

### LINKED ISSUE #225: [Feature Request] <Adding Loops, Decision making in Languages>
### Is your feature request related to a problem? Please describe.
There are algorithms and datastructures but there are no loops and decision making in languages at all which are also considered as fundamentals.

### Describe the solution you'd like
I want to add all the theory and examples of usage of loops and decision making.

### Describe alternatives you've considered
there are no alternatives

### Additional context
There only data types and variables.

image

**Would you like to work on this feature?**  
- Yes

### PR DESCRIPTION
**Pull request by PavanTeja2005**
### Description
I have added loops and decision making in languages for python and js

Fixes #225 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
### Please follow our docs structure. 
**Here are the guidelines:** 
1. Use the same headings and subheadings as the existing docs. 
2. Use the same formatting as the existing docs. 
3. Use the same tone and style as the existing docs.

**Comment by PavanTeja2005** [comment]
Please check the changes

**Comment by ajay-dhangar** [comment]
@PavanTeja2005, please sync your fork with the latest changes from the main repository. I've resolved the `backtracking-questions.md` error at line 56.

Here's what you need to do:
1. Fetch the latest updates from the main repository:
   ```
   git fetch upstream
   git merge upstream/main
   ```
2. Push the merged changes to your fork:
   ```
   git push origin your-branch
   ```
3. After syncing, resolve any remaining issues.

Please don't hesitate to let me know if you encounter any problems.

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
