### PR TITLE
solved #642

### LINKED ISSUE #642: [Feature Request] Hashing leetcode solutions
### Is your feature request related to a problem? Please describe.
Hashing leetcode solutions

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### LINKED ISSUE #720: [Feature Request] <Title of your feature>Add solutions to the quiz on arrays
### Is your feature request related to a problem? Please describe.
Add solutions to the quiz on arrays

### Describe the solution you'd like
Add solutions to the quiz on arrays
### Describe alternatives you've considered
Add solutions to the quiz on arrays
### Additional context
Add solutions to the quiz on arrays
---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #642

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir can you please merge this pull request

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
don't delete `README.md` file

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sir will #765 be merged sir

**Pull request merged**
