### PR TITLE
Create intersection-linked-lists.md

### LINKED ISSUE #569: Finding intersection node of two linked lists connected in y shape In cpp
🚀 Feature
There are two singly linked lists in a system. The end node of one of the linked list got linked to the second list, forming an inverted Y-shaped list. Write a program to get the point where two linked lists merge in Python

Linked Lists are one of the data structures to which basic to advanced coding interview questions are related. Hence as many as possible algorithms should be learned on linked lists.

Linked lists are a kind of data structure which have numerous applications. Many solutions can be made using linked lists as a data structure. Hence learning as many as possible algorithms related to it helps us resolve many issues in programming.

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by nishant4500**
### Description
i add new problem with solution of most asked question in interview

Fixes #569

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nishant4500** [comment]
@ajay-dhangar look into this

**Comment by nishant4500** [comment]
@ajay-dhangar any changes?

**Comment by nishant4500** [comment]
@ajay-dhangar please see this..

**Comment by nishant4500** [comment]
@ajay-dhangar can you please look into this i waant to save me streak

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
