### PR TITLE
Blockedqueue

### LINKED ISSUE #1357: Blocked queue algorithm
### Feature Name

Add blocked queue algorithm

### Feature Description

Feature: Blocked Queue Algorithm
A blocked queue algorithm is designed to manage and operate on queues where operations such as enqueue (adding an item) and dequeue (removing an item) might need to wait (or block) until certain conditions are met. This is especially useful in multithreading environments where multiple threads may need synchronized access to the queue.

Use Cases:
Multithreading: In scenarios where multiple threads need to access a shared queue, a blocked queue ensures that threads wait until they can safely perform operations, avoiding race conditions.
Producer-Consumer Problem: Producers add items to the queue, and consumers remove items from the queue. The blocked queue ensures that consumers wait if the queue is empty and producers wait if the queue is full.
Task Scheduling: In systems where tasks are scheduled based on availability, a blocked queue ensures that the scheduler waits until tasks are available for execution.

### Motivation

The inclusion of the blocked queue algorithm in the Algo repository addresses the need for a reliable and efficient method for managing queues in multithreading environments. Currently, the repository lacks an implementation that effectively handles concurrent access to queues, which is crucial for tasks requiring synchronization and coordination among multiple threads.

### PR DESCRIPTION
**Pull request by Subashree-selvaraj**
## 📥 Pull Request

Fixes #1357 

### Description
Added the blocked-queue.md file to include detailed explanations, pseudocode, and implementations for the blocked queue data structure in Python, C++, and Java. This update also includes a complexity analysis and an example section to illustrate the usage of the blocked queue.

### Checklist:

- [X] My code follows the style guidelines of this project
- [X]  I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Subashree-selvaraj — COMMENTED** [review]
added name in readme.md

**Comment by Subashree-selvaraj** [comment]
@ajay-dhangar Raised PR kindly check it!

**Comment by Subashree-selvaraj** [comment]
@ajay-dhangar Raised PR kindly check it

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Subashree-selvaraj** [comment]
@ajay-dhangar kindly check PR

**Pull request merged**
