### PR TITLE
enhanced scroll buttons

### LINKED ISSUE #1246: Enhancing Scroll to top feature
@ajay-dhangar 
The scroll to top feature is not looking good in the website
I would like to make it align with the website styling
Could you please assign it to me

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
### Description
I have enhanced the 2 scrolling buttons and removed extra chatbot feature

Fixes #1246 

Kindly check it out

scroll2 mp4

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar 
Could you please merge it

**Comment by ajay-dhangar** [comment]
Can you please inspect the page code and fix the bug for the chat box? Also, the chat box needs to be aligned to the left side of the page. The button is okay for now. You can comment out the left chat box and align the right chat box to the left. This will make the UI look okay.

**Comment by AswaniBolisetti** [comment]
@ajay-dhangar 
Hey I tried to align the chat box to the left , but i couldn't

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar Hey I tried to align the chat box to the left , but i couldn't

{7651A213-B89F-4295-9B3B-087E78797D8B}

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar Hey I tried to align the chat box to the left , but i couldn't

try style for `#chatbase-bubble-button`  id.

**Pull request closed without merging**
