### PR TITLE
Fixed Scale of contributors avatars

### LINKED ISSUE #1151: [Bug]: Size of User Avatar is enlarged
### Bug Summary

The user avatars on the Contributors page are larger than the designated container size, causing layout issues.

### Bug Description

The user avatar images are currently oversized and do not fit within their assigned container on the Contributors page. This leads to misalignment and an inconsistent user experience. The avatar should either be resized to fit within the box or appropriately styled to maintain consistent layout dimensions.

### Steps to Reproduce

- Go to the Contributors page: https://ajay-dhangar.github.io/algo/contributors
- Observe the user avatar for any contributor.
- Notice that the avatar is enlarged and exceeds the boundaries of its container.

### Expected Behavior

The avatar should fit within the container, maintaining a uniform and neat layout. Ideally, it should either scale down to the box size or be cropped to fit within a circular or square format.

### Actual Behavior

_No response_

### Screenshots or Logs (Optional)

image

### Severity

Minor - cosmetic or minor issue

### Environment

- [ ] Local Development
- [ ] Staging
- [ ] Production
- [ ] Other

### System Information (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Saaarthak0102**
# 📥 Pull Request

## Description
This pull request fixes the scale of contributor avatars to ensure consistency and proper alignment across the webpage. The adjustment resolves the issue where the avatars appeared disproportionate. No new dependencies were added, and the changes are localized to the CSS responsible for avatar scaling.

Fixes #1151 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Before : 
image

### After: 
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Saaarthak0102 — COMMENTED** [review]
reviewed

**Comment by Saaarthak0102** [comment]
please review and merge @ajay-dhangar!
Thanks!

**Comment by Saaarthak0102** [comment]
Please review and merge @ajay-dhangar !

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
