### PR TITLE
Added the features page 

### PR DESCRIPTION
**Pull request by vedhcet-07**
Sir i have added the features page and linked to footer also . please check it . Here is a ss . I am a beginner so just tried what i knew . Let me know if anything 
image
If everything is fine pls assign appropriate level and accept

### CODE REVIEW

**Comment by ajay-dhangar** [comment]
@vedhcet-07, please sync your fork with the latest changes from the main repository. I've resolved the `backtracking-questions.md` error at line 56.

Here's what you need to do:
1. Fetch the latest updates from the main repository:
   ```
   git fetch upstream
   git merge upstream/main
   ```
2. Push the merged changes to your fork:
   ```
   git push origin your-branch
   ```
3. After syncing, resolve any remaining issues.

Please don't hesitate to let me know if you encounter any problems.

**Comment by vedhcet-07** [comment]
sir i updated this thing . synced it . pls check

**Comment by vedhcet-07** [comment]
> sir i updated this thing . synced it . pls check . Sir level 2 if possible !

**Comment by ajay-dhangar** [comment]
> sir i updated this thing . synced it . pls check

The code should be written in a file named `index.tsx` in the `src/pages/features` directory, not `features.html` in the `src/pages/Features` directory.

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please avoid writing code in `.html`. Instead, use `.tsx` or `.jsx` as this project is React-based. For better clarity, think of it as a React project when creating pages for the Algo setup.

**Pull request closed without merging**
