### PR TITLE
Create Searching-Algorithms.md

### LINKED ISSUE #575: [Feature Request] Searching Algorithm
## 🚀 Feature Request
A searching algorithm is a method used to locate a specific element or value within a data structure, such as an array, list, or tree. Searching algorithms can be classified into two main categories: linear and binary searches.

1. Linear Search

Description: This is the simplest search algorithm. It sequentially checks each element in the data structure until it finds the target value or reaches the end of the structure.

Complexity:

Time Complexity: O(n), where n is the number of elements in the array.

Space Complexity: O(1), as it uses a constant amount of extra space.

Use Cases: Useful for unsorted or small datasets.

2. Binary Search

Description: This algorithm is more efficient than linear search but requires the data to be sorted. It repeatedly divides the search interval in half. If the target value is less than the middle element, it continues searching in the left half; if it's greater, it searches the right half.

Complexity:

Time Complexity: O(log n).

Space Complexity: O(1) for the iterative version and O(log n) for the recursive version (due to call stack).

Use Cases: Ideal for large, sorted datasets.

3. Other Searching Algorithms

Depth-First Search (DFS): Used in tree and graph structures, this algorithm explores as far down a branch as possible before backtracking.

Breadth-First Search (BFS): Also for trees and graphs, it explores all neighbor nodes at the present depth before moving on to nodes at the next depth level.

Interpolation Search: An improvement over binary search for uniformly distributed data, it estimates the position of the target value.

Exponential Search: Works on unbounded or infinite lists and finds the range where the target may exist before applying binary search.

Applications

Searching algorithms are fundamental in computer science and are widely used in various applications, including:

Database querying

Information retrieval systems

AI and machine learning

Networking and routing protocols

Choosing the right searching algorithm depends on the specific requirements of the application, such as the size of the dataset, whether it is sorted, and the need for efficiency.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: "I'm frustrated when I get question where this algorithm are used by default.

### Describe the solution you'd like
I will include all the searching algorithms.

### Additional context

---

**Would you like to work on this feature?**  
- [ I will work]Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Bhumika-00**
## 📥 Pull Request
Updated the searching algo

### Description
Added the searching algorithms inside the  arrays folder.

Fixes #575 

### Type of change

- [no ] Bug fix (non-breaking change which fixes an issue)
- [ no] New feature (non-breaking change which adds functionality)
- [ no] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ yes] Documentation update

### Checklist:

- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [yes ] I have added tests that prove my fix is effective or that my feature works
- [ yes] New and existing unit tests pass locally with my changes
- [no ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Bhumika-00** [comment]
The changes have been updated

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Bhumika-00** [comment]
Thanks a lot.

**Comment by Bhumika-00** [comment]
Please merge this

**Pull request merged**
