### PR TITLE
✨added STL✨

### LINKED ISSUE #507: ✨[Feature Request] <Adding stl features>✨
## 🚀 Feature Request

There are lot of stl algorithms i would love to add.
@ajay-dhangar can you please assign me this task.

---

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by trahulprabhu38**
fixes #507 
@ajay-dhangar can you please review this, thank you!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@ajay-dhangar can you please review this i need to make a new PR , thank you.

**Comment by trahulprabhu38** [comment]
@ajay-dhangar can you please review this i need to make a new PR , thank you.

**Comment by trahulprabhu38** [comment]
@ajay-dhangar bhaiya i have one more PR to make ,can you please review this thank you.

**Comment by trahulprabhu38** [comment]
@ajay-dhangar can you please review this , i have one more PR to make.

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar can you please review this , i have one more PR to make.

Sorry for the wait.

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
