### PR TITLE
solved #434  Added queue quiz and shown result 

### LINKED ISSUE #434: [Feature Request] Queues Quiz-Questions and marks to  be added
### Is your feature request related to a problem? Please describe.
Queues Quiz-Questions and marks to  be added

### Describe the solution you'd like
Queues Quiz-Questions and marks to  be given 

### Describe alternatives you've considered
Queues Quiz-Questions and marks to  be added

### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description

Fixes #434 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
kindly,consider this as level3 for the work i done 

https://github.com/user-attachments/assets/f8f84622-f895-4e50-87f5-de0c33441641

**Comment by ajay-dhangar** [comment]
@KapuluruBhuvaneswariVspdbct, can you update the UI for the queue quiz to make it more interactive? This will make it easier for users to interact with the quiz.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
