### PR TITLE
Addition of BackToTop Button | Issue #112

### LINKED ISSUE #112: [Feature Request] Addition of Back-To-Top Button
### Is your feature request related to a problem? Please describe.
Yes, addition of back to top button ensures the better navigation from bottom to top in just single click and enhance the interaction between the user and web app.

### Describe the solution you'd like
I want to add Back-To-Top button in the webapp.

**Would you like to work on this feature?**  
- [X] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Shariq2003**
### Description
I have added a back to top button in the web app.

https://github.com/user-attachments/assets/8c0b1728-a01f-41a2-a1fd-69ab30cc32d3

Fixes #112 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — APPROVED** [review]
👍

**Comment by Shariq2003** [comment]
> 👍
Merging is left

**Comment by ajay-dhangar** [comment]
This is a good start. I think you can improve the UI/UX by using https://github.com/CodeHarborHub/codeharborhub.github.io/tree/main/src/components/Buttons. You can also add a button at the bottom of the page.

**Comment by Shariq2003** [comment]
> This is a good start. I think you can improve the UI/UX by using https://github.com/CodeHarborHub/codeharborhub.github.io/tree/main/src/components/Buttons. You can also add a button at the bottom of the page.

@ajay-dhangar sir, so have to update ?

**Comment by ajay-dhangar** [comment]
> > This is a good start. I think you can improve the UI/UX by using https://github.com/CodeHarborHub/codeharborhub.github.io/tree/main/src/components/Buttons. You can also add a button at the bottom of the page.
> 
> @ajay-dhangar sir, so have to update ?

You can try to work on the UI/UX by using the given link. You can also add a button at the bottom of the page.

**Comment by Shariq2003** [comment]
@ajay-dhangar sir, I have added both the buttons just like in the above repo but with smooth scrolling 😁

**Review by ajay-dhangar — APPROVED** [review]
Done 💖

**Pull request merged**
