### PR TITLE
Added Kadane's Algorithm

### PR DESCRIPTION
**Pull request by Bhumika-00**
Kadane's Algorithm is a well-known algorithm in computer science that efficiently finds the maximum sum of a contiguous subarray within a one-dimensional array of integers. The beauty of this algorithm lies in its simplicity and its linear time complexity of O(n), making it suitable for large datasets.

### Description
I have added Kadane's Algorithm into the project as a n ew folder as requested  by the admin along with its json file.

Fixes # (issue number)

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ YES] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ YES] Documentation update

### Checklist:

- [ YES] My code follows the style guidelines of this project
- [ YES] I have performed a self-review of my code
- [ YES] I have commented my code, particularly in hard-to-understand areas
- [ YES] I have added tests that prove my fix is effective or that my feature works
- [ YES] New and existing unit tests pass locally with my changes
- [YES ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Bhumika-00** [comment]
Both kadane and hare tortoise approach is completed

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Compare your code with our docs structure. Make sure your code is well-structured and follows our guidelines. Also, use `mdx` syntax for our `.md` files.

**Comment by Bhumika-00** [comment]
Okay

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Bhumika-00** [comment]
Thank you so  much

**Pull request merged**
