### PR TITLE
Updated Twitter icon

### LINKED ISSUE #32: [Bug] <Wrong Icons Added>
The footer icon of twitter is old . it needs to be updated to x . 
image

I would like to work on this . So please assign this work to me under hacktoberfest and gssoc expecting a positive reply from your side

### PR DESCRIPTION
**Pull request by vedhcet-07**
Updated twitter icon pls check and let me know

### CODE REVIEW

**Review by ajay-dhangar — APPROVED** [review]
Done

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
can you delete `webpack.yml` file

**Comment by vedhcet-07** [comment]
> can you delete `webpack.yml` file

Sir i deleted it pls check

**Review by ajay-dhangar — APPROVED** [review]
Done👍

**Pull request merged**
