### PR TITLE
Minimum cost spanning tree using kruskal's and prim's  #503

### LINKED ISSUE #503: [Feature Request] <Minimum cost spanning tree using kruskal's and prim's >
### Is your feature request related to a problem? Please describe.

I'm frustrated when I need to compare and visualize the results of Kruskal's and Prim's algorithms for finding the Minimum Cost Spanning Tree (MST) in graphs, especially in large datasets. Implementing both algorithms separately and ensuring correct results can be tedious and time-consuming.

### Describe the solution you'd like
I would like a feature in the application that implements both Kruskal's and Prim's algorithms to compute the Minimum Cost Spanning Tree (MST) for any given graph. The solution should:

Allow users to input graphs in different formats (adjacency list/matrix).
Provide a visual comparison of the results from both algorithms.
Output the total cost and the edges included in the MST for both algorithms.
Offer performance metrics to compare the efficiency of Kruskal's and Prim's algorithms based on graph size and structure.

### Describe alternatives you've considered
Writing separate programs for Kruskal's and Prim's algorithms and comparing the results manually.
Using external libraries or tools that implement MST algorithms but lack direct comparison features.
Implementing only one of the algorithms, which would limit flexibility.
### Additional context
The feature should support both directed and undirected graphs. It should also allow real-time user interaction, such as modifying graph edges and weights to observe changes in the MST dynamically.

---

**Would you like to work on this feature?**  
- [X ] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by Ananya-vastare**
### Description
Minimum Spanning Tree (MST) algorithms are essential in graph theory, helping to connect all vertices in a weighted graph while minimizing the total edge weight. These algorithms, including Prim's and Kruskal's, employ a greedy approach to efficiently determine the optimal set of edges that forms the MST. By ensuring no cycles are created and all vertices remain connected, MSTs have practical applications in network design, resource optimization, and clustering analysis. This post explores the fundamental concepts, characteristics, and implementations of MST algorithms, providing insights into their functionality and relevance in various fields.

Fixes #503

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@ajay-dhangar please let me know if I have to make any changes thank you and please add the level to this thank you

**Comment by Ananya-vastare** [comment]
@ajay-dhangar I have resolved the conflict also add the hacktoberfest label thank you

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar I have resolved the conflict also add the hacktoberfest label thank you

Our repo is Excluded in hacktoberfest

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Ananya-vastare** [comment]
@ajay-dhangar will it be merged?!?

**Pull request merged**
