### PR TITLE
Add documentation for SQL aggregate functions

### LINKED ISSUE #1070: [Idea]: Add Documentation for SQL Aggregate Functions
### Idea Title

Add Documentation for SQL Aggregate Functions

### Idea Description

The website currently lacks documentation for SQL aggregate functions, making it challenging for users to effectively utilize these essential tools in their queries.

Importance of Documentation:
SQL aggregate functions like **SUM, AVG, COUNT, MAX**, and MIN are vital for data analysis. Proper documentation will:

- Clarify Functionality: Define each function and its operation.
- Provide Examples: Illustrate usage with practical examples.
- Highlight Use Cases: Show relevance in real-world scenarios.
- Optimize Performance: Discuss best practices for large datasets.
 

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [ ] Other

### Implementation Suggestions (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Kunj05**
### Description
This PR introduces comprehensive documentation for SQL aggregate functions, addressing the current gap in our resources. The addition aims to help users better understand and utilize these essential functions in their queries.

Changes Made:

- Added comprehensive documentation for SQL aggregate functions, including definitions and explanations for each function.
- Included practical examples demonstrating the usage of the functions: SUM, AVG, COUNT, MAX, and MIN.
- Highlighted various use cases to illustrate the relevance of these functions in real-world scenarios.
- Provided best practices for optimizing performance when working with large datasets.
- 
Fixes #1070 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
you need to close your code example also, ```` ``` ````

**Comment by Kunj05** [comment]
@ajay-dhangar u can check i have close all the code with ```

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by Kunj05** [comment]
@ajay-dhangar can u add all the required labels like enhancement, hacktoberfest etc

**Pull request merged**
