### PR TITLE
solved #431   #433 Added quiz on arrays,stack and results

### LINKED ISSUE #431: [Feature Request] <Title of your feature>Add Questions and marks to the quiz on arrays
### Is your feature request related to a problem? Please describe.
Wanted to add  array quiz questions  and show score at the end 
### Describe the solution you'd like
Adding array quiz questions 
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### LINKED ISSUE #433: [Feature Request] Stacks Quiz-Questions and marks to  be added
### Is your feature request related to a problem? 
Please describe. Stacks Quiz-Questions and marks to  be added
### Describe alternatives you've considered
 Stacks Quiz-Questions and marks to  be added
### Additional context

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
### Description
Successfully created the Quiz on arrays and results  displayed
Fixes #431
image
image
image

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
kindly consider as level2 for work done by me

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir,kindly consider this as level2 for the work and efforts made by me

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
please merge this

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
dont delete

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
solved both #431 and #433 consider this as level 2 sir and please allot the marks for 2 commits as i made both of them in same pull request instead of creating 2 pull requesrs

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
thank you

**Pull request merged**
