### PR TITLE
Added algorithm for [HashMap]

### LINKED ISSUE #205: [Feature Request] HashMap data structure
## 🚀 Feature Request

Please assign me this. Implementation of hashmap along with how to solve problems using hashmap.

### PR DESCRIPTION
**Pull request by KomalKalra05**
### Description
I add a new feature of HashMap data structure explaining its implementation and various list of problems that can be solved using this data structure

Fixes #205

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
don't modify/update  `package-lock.json` file you need reset code

**Comment by KomalKalra05** [comment]
Can you review it again?

**Comment by ajay-dhangar** [comment]
@KomalKalra05, not edit any code in `package-lock.json` file or reset all code in `package-lock.json` file

**Comment by KomalKalra05** [comment]
I did not change any of it

**Comment by ajay-dhangar** [comment]
> I did not change any of it

@KomalKalra05, please sync your fork with the latest changes from the main repository. I've resolved the `backtracking-questions.md` error at line 56.

Here's what you need to do:
1. Fetch the latest updates from the main repository:
   ```
   git fetch upstream
   git merge upstream/main
   ```
2. Push the merged changes to your fork:
   ```
   git push origin your-branch
   ```
3. After syncing, resolve any remaining issues.

Please don't hesitate to let me know if you encounter any problems.

**Comment by KomalKalra05** [comment]
I followed the steps 
Can you review now?

**Comment by ajay-dhangar** [comment]
> I did not change any of it

can you resit your `package-lock.json` fine?

**Pull request closed without merging**
