### PR TITLE
Added the algorthms 

### LINKED ISSUE #568: Adding few important algorithms
## @ajay-dhangar , I want to add some algorithms

1) Strand sort in sorting algorithms

2) Priority Scheduling ,multilevel queue scheduling and least recently used (LRU)

3) Tail recursion,Non tail recursion , tree recursion,mutual recursion

assign this to me under gssoc extd and hacktoberfest

### PR DESCRIPTION
**Pull request by aditya07389**
hey @ajay-dhangar 
Fixes #568 

### Description

Hey i have added all the algorithms i mentioned in the issue in the respective folders 
please check and tell me if any changes are required , I have also added the component for seo optimization as guided for each  . md file I created. 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [✅ ] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [✅ ] New and existing unit tests pass locally with my changes
- [✅ ] Any dependent changes have been merged and published in downstream modules

Thankyou 
Pls add the labels gssoc extd , hacktoberfest

### CODE REVIEW

**Comment by aditya07389** [comment]
@ajay-dhangar  can u please check and tell me if its fine

**Comment by aditya07389** [comment]
@ajay-dhangar can u please add a higher label?

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
We need on top for every `.md` file for our docs

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

**Comment by aditya07389** [comment]
ill do it @ajay-dhangar

**Comment by aditya07389** [comment]
@ajay-dhangar kindly check now !

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by aditya07389** [comment]
Hey @ajay-dhangar please add a higher label

**Comment by aditya07389** [comment]
@ajay-dhangar can u please add a higher level label ?

**Comment by aditya07389** [comment]
@ajay-dhangar  please add a higher level label

**Pull request merged**
