### PR TITLE
Create Dijkstra’s Algorithm.md

### PR DESCRIPTION
**Pull request by vishantrathi**
### Description
Added new algorithm to the repo

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please update your code based on our format and syntax

**Review by vishantrathi — COMMENTED** [review]
Changes have been done as instructed by maintainer
please review and merge

**Comment by vishantrathi** [comment]
Changes have been done as instructed by maintainer
please review and merge

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
