### PR TITLE
BooleanExpressionParser

### PR DESCRIPTION
**Pull request by ananydev**
### Description
This code defines a BooleanExpressionParser class that evaluates boolean expressions with custom operators in Java. The main method, parseBoolExpr, interprets expressions made of & (AND), | (OR), and ! (NOT) operators, where t represents true, and f represents false. Expressions are parsed from left to right, leveraging stacks for nested expressions.

How It Works:
Expression Parsing: The method iterates through the expression. For characters other than ), it simply pushes them to the stack, ignoring commas.
Expression Evaluation: Upon encountering ), it pops values into a buffer stack until it reaches the matching (. Based on the operator before the (:
& evaluates to true if all values in the buffer are t.
| evaluates to true if at least one value is t.
! negates a single value.
Result Storage: After calculating the result, it pushes t or f back onto the stack for further evaluations.
Final Output: The stack's top element at the end provides the overall evaluation of the expression.
Examples:
&(|(f)) evaluates to false as it checks the AND condition on the OR result of a single f.
|(f,f,f,t) evaluates to true as at least one element (t) satisfies the OR condition.
!(|(f,t)) evaluates to false, negating the OR result of f and t.
Fixes # (issue number)

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Please write your code in markdown and save the file with a `.md` extension. When writing your code, please follow our established format.

**Review by ananydev — COMMENTED** [review]
I HAVE MADE CHANGES . KINDLY ACCEPT PR

**Review by ajay-dhangar — CHANGES_REQUESTED** [review]
Thank you for your contribution. To ensure consistency, please follow our documentation formatting and syntax. It is also important to follow Markdown (.md) syntax.

**Review by ananydev — COMMENTED** [review]
I have made necessary changes . kindly review again pls

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
