### PR TITLE
Fractional Knapsack Problem  added (fixes #1912)

### LINKED ISSUE #1912: [Idea]: Fractional Knapsack Problem
### Idea Title

add a new greedy algorithm

### Idea Description

To maximize profit by selecting items with weights and profits, allowing fractional items.

### Potential Benefits

- [X] Improves user experience
- [X] Enhances learning
- [X] Adds a new feature
- [X] Improves code quality
- [ ] Other

### Implementation Suggestions (Optional)

@ajay-dhangar can you assign this to me??

### PR DESCRIPTION
**Pull request by laxmikandivalasa**
### Description
To maximize profit by selecting items with weights and profits, allowing fractional items.

Fixes #1912 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar can you check this pr!!

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar can't you merge this now??

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar will this count in the leaderboard?

**Comment by ajay-dhangar** [comment]
> @ajay-dhangar will this count in the leaderboard?

Yes

**Review by ajay-dhangar — APPROVED** [review]
👍

**Comment by laxmikandivalasa** [comment]
Thank you!

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar What if the pending pr(for this pr) in the open source practice project is in open?

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar can these prs get merged now??

**Comment by laxmikandivalasa** [comment]
@ajay-dhangar Will this get added in the leaderboard ??

**Pull request merged**
