### PR TITLE
All "Learn more" buttons below algorithm are updated now (Revised)

### LINKED ISSUE #253: Learn More button is not Functional
### Describe the bug
The "Learn More" button below algorithms (e.g., Binary Search) currently scrolls the page up instead of directly linking to the relevant algorithm documentation. This creates unnecessary navigation steps for the user. The button should instead link directly to the algorithm's detailed page.

### To Reproduce
Go to the [site](https://ajay-dhangar.github.io/algo/).
Scroll down to the Binary Search algorithm.
Click "Learn More" and observe that the page scrolls up instead of opening the detailed documentation.

### Expected behavior
Clicking the "Learn More" button should take the user directly to the relevant algorithm's page, such as:

Binary Search: https://ajay-dhangar.github.io/algo/docs/binary-search/iterative-binary-search-DSA

### Additional context
Solution: Update the "Learn More" button's href attribute to link directly to the corresponding algorithm documentation.

---

**Would you like to work on this issue?**  
- [x] Yes , I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Saaarthak0102**
### Description

Updated the "Learn More" buttons associated with algorithms to directly link to their corresponding detailed pages, improving user navigation by eliminating unnecessary scrolling. Each button now takes users directly to the relevant algorithm page (e.g., iterative binary search).

Additionally, the following changes were made to popular algorithms:

Breadth-First Search (BFS): Changed the implementation to use recursion.
Depth-First Search (DFS): Updated the implementation to utilize linked lists.

### Reason for change

The original BFS and DFS implementations lacked accompanying .md files for explanation; only problem-solving resources were available. The "Learn More" buttons should direct users to educational content rather than just problem-solving pages.

Fixes #253 : https://youtu.be/_Iu9D0k3vHk

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saaarthak0102** [comment]
@ajay-dhangar I have modified all the necessary files, please review it!

thanks

**Review by Saaarthak0102 — COMMENTED** [review]
Reviewed!

**Review by Saaarthak0102 — COMMENTED** [review]
Reviewed!

**Comment by Saaarthak0102** [comment]
please review @ajay-dhangar

**Review by ajay-dhangar — APPROVED** [review]
done

**Comment by Saaarthak0102** [comment]
> done

Thank you so much!

**Pull request merged**
