### PR TITLE
Added all 2D array algos

### LINKED ISSUE #630: [Feature Request] Want to add 2D array
### Is your feature request related to a problem? 
In your array section want to add 2D arrays

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No  

Kindly assign me to do it @ajay-dhangar

### PR DESCRIPTION
**Pull request by Mansi07sharma**
### Description
Add the whole detail about 2D array  added in arrays folder

Fixes #630 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Mansi07sharma** [comment]
@ajay-dhangar Can you plz check it and review it. @shivay-coding

**Comment by Mansi07sharma** [comment]
@ajay-dhangar sir please check it and add labels level2 or level3 Requesting sir.

**Comment by Mansi07sharma** [comment]
@ajay-dhangar Could you please review it? Kindly merge it if it is correct  @shivay-coding

**Review by ajay-dhangar — APPROVED** [review]
Done

**Pull request merged**
