### PR TITLE
Created a contributors page, added it on navbar too

### LINKED ISSUE #748: [Feature Request] Add contributors page!
## Is your feature request related to a problem? Please describe.

A dedicated contributors page would allow users to see who has contributed to the project, enhancing community recognition and transparency.

## Describe the solution you'd like

I would like to implement a dedicated "Contributors" page that lists all individuals who have contributed to the project. This page could include details such as:

Contributor names
Profile links (GitHub or social media)
Contribution types (e.g., code, documentation, design)
Contribution statistics (e.g., number of commits, pull requests, issues)

##Describe alternatives you've considered

GitHub's built-in contributors graph: This provides some information but lacks a comprehensive view and does not offer personal links or detailed stats.

Using a README section: Listing contributors in the README is possible, but it may not be as visually appealing or organized as a dedicated page.

## Additional context

This feature can improve community engagement and make it easier for newcomers to connect with contributors. Here are a couple of ideas for the page design:

A grid layout displaying contributor avatars and names.
A filter/search function to easily find contributors.

### PR DESCRIPTION
**Pull request by Saaarthak0102**
# 📥 Pull Request

Fixes issue #748 

## Description

- Created a Contributors page to display the list of contributors.
- Integrated an API to fetch the contributors dynamically and added Axios in the dependencies for making HTTP requests.
- Added a "Contributors" link in the navigation bar for easy access to the page.

## Screenshots

image
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saaarthak0102** [comment]
please review @ajay-dhangar.
Also, it would be great for me if you assign level 2 for this PR for the extra efforts made as it was not just about the documentation update!
Thanks!

**Review by Saaarthak0102 — COMMENTED** [review]
Reviewed

**Review by ajay-dhangar — APPROVED** [review]
Done

**Comment by ajay-dhangar** [comment]
Please resolve the conflicts in `package-lock.json`. Once the conflicts are resolved, I will merge your changes.

**Comment by Saaarthak0102** [comment]
raising new PR

**Pull request closed without merging**
